# Created by: Zach Leslie <ports@zleslie.info>

PORTNAME=	fluent-bit-go
PORTVERSION=	g20190926
CATEGORIES=	sysutils

MAINTAINER=	zach@zleslie.info
COMMENT=	Go bindings for fluent-bit

LICENSE=	APACHE20

BUILD_DEPENDS=	git:devel/git

USES=		go
USE_GITHUB=	yes

GH_ACCOUNT=	fluent
GH_TAGNAME=	ea13c021

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${PORTNAME}
GO_TARGET=	github.com/${GH_ACCOUNT}/${PORTNAME}

.include <bsd.port.mk>
